name: Release Alpha

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    uses: ./.github/workflows/build-pyinst.yml
    with:
      version: 'alpha'
      target_platform: 'all'
      create_release: 'yes'
    secrets: inherit
