name: Release Build All

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: '发布版本号（留空则发布为 Alpha）'
        required: false
        type: string
      build_type:
        description: '构建方式'
        required: true
        type: choice
        options:
          - pyinstaller
          - cxfreeze
          - nuitka
        default: 'pyinstaller'
      target_platform:
        description: '目标平台'
        required: true
        type: choice
        options:
          - windows
          - linux
          - macos
          - all
        default: 'all'

permissions:
  contents: write

jobs:
  release-pyinstaller:
    if: github.event_name == 'push' || inputs.build_type == 'pyinstaller'
    uses: ./.github/workflows/build-pyinst.yml
    with:
      version: ${{ github.event_name == 'push' && 'alpha' || inputs.version }}
      target_platform: ${{ github.event_name == 'push' && 'all' || inputs.target_platform }}
      create_release: 'yes'
    secrets: inherit

  release-cxfreeze:
    if: github.event_name != 'push' && inputs.build_type == 'cxfreeze'
    uses: ./.github/workflows/build-freeze.yml
    with:
      version: ${{ inputs.version }}
      target_platform: ${{ inputs.target_platform }}
      create_release: 'yes'
    secrets: inherit

  release-nuitka:
    if: github.event_name != 'push' && inputs.build_type == 'nuitka'
    uses: ./.github/workflows/build-nuitka.yml
    with:
      version: ${{ inputs.version }}
      target_platform: ${{ inputs.target_platform }}
      create_release: 'yes'
    secrets: inherit
